export const CREDENTIALS_CHANGE = 'CREDENTIALS_CHANGE';

export const BACKEND_DETAILS_REQUEST = 'BACKEND_DETAILS_REQUEST';
export const BACKEND_DETAILS_SUCCESS = 'BACKEND_DETAILS_SUCCESS';
export const BACKEND_DETAILS_ERROR = 'BACKEND_DETAILS_ERROR';
